DB	:= skuapso
DBUSER	:= skuapso
DBHOST	:= /var/run/postgresql
DBPORT	:= 5434

.PHONY: show_config

show_config:
	@echo "Current configuration:"
	@echo "\tdatabase:\t$(DB)"
	@echo "\tdatabase user:\t$(DBUSER)"
